feat: 모달에 들어갈 폼 컴포넌트를 구현한다
car-ffeine/admin pull request #12
Opened 2023-08-11 07:45 UTC by feb-dain

## 📄 Summary

> 모달에 들어갈 폼 컴포넌트를 구현한다.
 - `input` 초기 value는 현재 정보
 - `input`을 눌러 바로 수정 가능하도록 구현

## 🕰️ Actual Time of Completion

> 4시간

## 🙋🏻 More

>

close #10

2023-08-11 07:57 UTC, drunkenhw requested changes
멋집니다

2023-08-11 07:57 UTC, drunkenhw commented on src/components/Form/Form.tsx
> +    console.log(getTypedObjectFromEntries([...formData]));
console.log()

2023-08-11 07:57 UTC, drunkenhw commented on src/components/Form/Form.tsx
> +  element: StationEditProps;
element는 여러개가 들어오지 않나요?

2023-08-11 07:57 UTC, drunkenhw commented on src/components/Form/Form.tsx
> +    }
이 부분은 더 상위에서 검사해서 넣어주면 안되나요?

2023-08-11 07:57 UTC, drunkenhw commented on src/components/Form/Form.tsx
> +    }
이렇게 비교해도 괜찮아요? object.is는 ==으로 비교한다던데

2023-08-11 07:57 UTC, drunkenhw commented on src/components/Table/AdminTableHead.tsx
> +  categoryList: readonly (typeof STATION_DETAILS_CATEGORIES)[keyof typeof STATION_DETAILS_CATEGORIES][];
type of keyof type of?  코드 엄청 복잡하네요

2023-08-11 07:59 UTC, feb-dain commented on src/components/Form/Form.tsx
> +    }
console.log(Object.is('1', 1));
// Expected output: false

2023-08-11 16:34 UTC, feb-dain commented on src/components/Form/Form.tsx
> +  element: StationEditProps;
elements안에 있는 요소라 element라고 했는데 더 좋은 이름 있으면 추천해주세요~

2023-08-12 05:45 UTC, drunkenhw approved these changes
초보라 모르는 것들 질문 위주로 남겼습니다 감사합니다

2023-08-12 05:45 UTC, drunkenhw commented on src/common/Toast/Toast.stories.tsx
> +      <S.Toast color="primary">이삭 토스트</S.Toast>
ㅋㅋ;;

2023-08-12 05:45 UTC, drunkenhw commented on src/components/Form/Form.tsx
> +  element: StationEditProps;
values?

2023-08-12 05:45 UTC, drunkenhw commented on src/components/Form/Form.tsx
> +    }
show toast라고 하드코딩되는 것 보다 상위에서 어떤 행동을 할 것인지에 대해 넣어주는 것은 어떤가요?
그러면 좀 더 유연할 것 같아요 toast가 튀어나올지, 갑자기 alert창이 나올지는 form이 몰라도 되는 부분이라고 생각이 들어서요

2023-08-12 05:45 UTC, drunkenhw commented on src/components/Form/Form.tsx
> +    }
리액트를 잘 몰라서 그냥 제 생각을 남겨봤습니다.

2023-08-12 05:45 UTC, drunkenhw commented on src/components/Form/Form.tsx
> +          return (
이 분기문을 다 다른 컴포넌트로 만들면 과한 부분일까요..?

2023-08-12 05:45 UTC, drunkenhw commented on src/components/Form/Form.tsx
> +          return (
제가 초보라 한번에 어떤 그림이 나올지 그려지지 않아서요 ㅜ

2023-08-12 05:45 UTC, drunkenhw commented on src/stores/toastStore.ts
> +   */
이런 주석은 꼭 필요할까요? 전 안봐도 이해할 수 있을 것 같아서요

2023-08-12 05:45 UTC, drunkenhw commented on src/stores/toastStore.ts
> +   */
naming을 워낙에 잘하셔서

2023-08-12 07:14 UTC, feb-dain commented on src/stores/toastStore.ts
> +   */
Jsdocs를 사용해서 넣은 이유는 함수 위에 마우스를 올렸을 때 기본값이 뭔지 알면 좋겠다고 생각해서 넣은 거예여! 기본값은 넣지 않아도 되는 거니까 확인하고 필요없는 props를 안 넣을 수 있게요

2023-08-12 07:16 UTC, feb-dain commented on src/components/Form/Form.tsx
> +          return (
컴포넌트 나누면 가독성이 더 좋아지겠지만 지금은 다른 거 먼저 만드는게 우선이라 일단 놔뒀습니다

2023-08-12 08:15 UTC, feb-dain commented on src/components/Form/Form.tsx
> +  element: StationEditProps;
음... 나중에 더 구체적인 이름으로 바꾸면 좋을 것 같아요

2023-08-12 08:23 UTC, merged